config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resource :session


  resources :users


  get 'signup' => 'users#new'



  #Passing routes manually with scope parameter
  #get "events/past" => "events#index", scope: "past"
  #get "events/free" => "events#index", scope: "free"

  #Passing routes manually but with a block. Better.
  # ["past", "free"].each do |scope|
  #     get "events/#{scope}" => "events#index", scope: scope
  # end

  get "events/filter/:scope" => "events#index", as: :filtered_events
  get "/css" => 'events#css'

  root 'events#index'
  resources :events do
    resources :registrations
    resources :likes
  end



end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  #Lambda. Query code is evaluated each time.
  scope :past, -> {where('starts_at < ?', Time.now).order(:starts_at)}
  scope :upcoming, -> {where('starts_at > ?', Time.now).order(:starts_at)}
  scope :free, -> {where(price: 0).order(:name)}
  scope :recent, ->(max=1) {past.limit(max)}

  validates :name, :location, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}, presence: true
  validates :description, length: {minimum: 20}
  validates :location, presence: true

  #To Param is used to make friendly URLS for this Event Model.
  def to_param
    "#{id}-#{name.parameterize}"
  end


  def free?
    price.blank? || price.zero?
  end

  def spots_left
    capacity - registrations.size
  end

  def sold_out
    spots_left.zero?
  end

  def anyone_registered
    registrations.any?
  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def css

  end


  def index

    case params[:scope]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    else
      @events = Event.upcoming
    end

  end

  def show
    @event = Event.find(params[:id])
    @registrations = @event.registrations.all
    @likers = @event.likers
    @categories = @event.categories
  end

  def edit
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path
      flash[:notice] = "Event Updated!"
    else
      render :edit
    end

  end

  def create
    #@event = Event.new(params[:event])
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
      flash[:notice] = "Event Created!"
    else
      render :new
    end

  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path

  end

private

  def event_params
    params.require(:event).permit(:name, :description, :location,
                                  :price, :starts_at, :image_file_name, :capacity,
                                  category_ids: [])
  end


end

app/helpers/events_helper.rb
module EventsHelper

  def price_view(event)
    if event.free?
      "FREE"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def register_for(event)
    if event.registrations.where(user: current_user).exists?
      link_to("Unregister", event_registration_path(event), method: :delete, class:"text-white btn btn-secondary mr-2")
    elsif event.sold_out
      content_tag(:a, "Sold Out", class:"text-white btn btn-secondary mr-2")
    else
      link_to "Register", new_event_registration_path(@event), class:"btn btn-primary mr-2"
    end
  end

  def format_date(event)
    event.starts_at.strftime("%b %d, %Y")
  end

  def format_time(event)
    event.starts_at.strftime("%l:%M %p")
  end

  def format_date_month(event)
    event.starts_at.strftime("%^b")
  end

  def format_date_day(event)
    event.starts_at.strftime("%d")
  end

end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%=render 'shared/errors', object: @event%>
      <%= form_for(@event) do |form|%>
        <div class="form-group">
          <%=form.label :name %>
          <%=form.text_field :name, class:"form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%=form.label :location %>
          <%=form.text_field :location, class:"form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%=form.label :price %>
          <%=form.text_field :price, class:"form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%= form.label "Date" %><br>
          <%= form.datetime_select :starts_at, class:"form-control" %>
        </div>


        <div class="form-group">
          <%=form.label :description %>
          <%=form.text_area :description, class:"form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%=form.label :capacity %>
          <%=form.text_field :capacity, class:"form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%=form.label :image_file_name %>
          <%=form.text_field :image_file_name, class:"form-control", autofocus: true %>
        </div>

        <div class="form-check my-2">

          <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
            <%=b.check_box(class:"form-check-input") %>
            <%=b.label(class:"form-check-label mr-4") %>
          <%end %>

        </div>


        <%=form.submit class:"btn btn-primary" %>
      <%end %>

    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<div class="container">

  <div class="row d-flex justify-content-center justify-content-md-end">
    <%=link_to "Past", filtered_events_path(:past), class:"btn btn-outline-secondary mr-2" %>
    <%=link_to "Free", filtered_events_path(:free), class:"btn btn-outline-secondary mr-2" %>
    <%=link_to "Upcoming", filtered_events_path(:past), class:"btn btn-outline-secondary mr-2" %>
  </div>

  <div class="row">
  <%@events.each do |event| %>
      <div class="event-wrap col-md-6 col-lg-4 mb-5 pt-2">
        <a href="<%=event_path(event) %>"><%= image_tag(event.image_file_name, class: "event-image img-fluid rounded")%></a>
        <div class="bottom-wrapper p-3 d-flex">
          <div class="date-wrap mr-2">
            <div class="month text-muted"><%=format_date_month(event)%></div>
            <div class="date text-muted"><%=format_date_day(event) %></div>
          </div>

          <div class="text-wrap">
            <%=link_to event.name, event_path(event), class:"h5 text-decoration-none" %>
            <p class="text-muted"><%=event.description %></p>
            <div class="small"><%=format_date(event)%> at <%=format_time(event)%></div>
            <div class="small"><%=event.location%></div>
            <div class="price mt-2 d-flex">
              <span class="badge-primary p-1 rounded "><%=price_view(event)%></span>
            </div>
          </div>
        </div>
      </div>
      <%end %>
  </div>


</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<%content_for(:title, @event.name) %>

<div class="container">
  <div class="row">

    <div class="col-md-12 col-lg">
      <%= image_tag(@event.image_file_name, class: "card-img-top")%>
    </div>
    <div class="col">

      <table class="table table-striped">
        <thead>
        <tr>

        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">Name</th>
          <td><%=@event.name %></td>
        </tr>

        <tr>
          <th scope="row">Description</th>
          <td><%=@event.description %></td>
        </tr>

        <tr>
          <th scope="row">Location</th>
          <td><%=@event.location %></td>
        </tr>

        <tr>
          <th scope="row">Price</th>
          <td><%=price_view(@event) %></td>
        </tr>

        <tr>
          <th scope="row">Date</th>
          <td><%= format_date(@event)%></td>
        </tr>

        <tr>
          <th scope="row">Time</th>
          <td><%= format_time(@event)%></td>
        </tr>

        <tr>
          <th scope="row">Seats Remaining</th>
          <td><%= @event.spots_left %></td>
        </tr>



        </tbody>
      </table>

      <div class="d-flex">
        <%if current_user %>
          <%=register_for(@event) %>
        <%end %>

        <%if current_user && current_user.admin? %>
          <%= link_to "Edit", edit_event_path(@event), class:"btn btn-primary mr-2" %>
          <%= link_to "Delete", event_path, class:"btn btn-danger mr-2", method: :delete, data:{confirm:"Are you sure?"} %>
        <%end %>

        <%if current_user %>
          <% if current_user.likes.find_by(event_id: @event.id) %>
            <%=link_to "Unlike", event_like_path(@event), method: :delete, class:"btn btn-primary" %>
          <%else %>
            <%=link_to "Like", event_likes_path(@event), method: :post, class:"btn btn-primary"%>
          <%end %>
        <%end %>

      </div>

    </div>
    <div class="col-sm-12 col-lg-2 mt-4 mt-lg-0">

      <%if current_user %>
        <%if @event.anyone_registered %>
          <div class="row flex-column">
            <div class="col">
            <h2 class="h5">Attendees (<%=@registrations.count %>)</h2>
              <%@registrations.each do |registration| %>
                <div class="d-flex">
                  <i class="material-icons mr-1">person</i>
                  <p class="mb-1"><%=link_to registration.user.name, registration.user %></p>
                </div>
              <%end %>
            </div>

          </div>
        <%end %>
      <%end %>


      <%if @likers.any? %>
        <div class="row flex-column mt-3">
          <div class="col">
            <h2 class="h5">Likes</h2>
            <%@likers.each do |liker| %>
              <div class="d-flex">
                <i class="material-icons mr-1">favorite</i>
                <p class="mb-1"><%=link_to liker.name, liker%></p>
              </div>
            <%end %>
          </div>

        </div>
      <%end %>





    </div>

  </div>
</div>