config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resource :session


  resources :users


  get 'signup' => 'users#new'



  #Passing routes manually with scope parameter
  #get "events/past" => "events#index", scope: "past"
  #get "events/free" => "events#index", scope: "free"

  #Passing routes manually but with a block. Better.
  # ["past", "free"].each do |scope|
  #     get "events/#{scope}" => "events#index", scope: scope
  # end

  get "events/filter/:scope" => "events#index", as: :filtered_events
  get "/css" => 'events#css'

  root 'events#index'
  resources :events do
    resources :registrations
    resources :likes
  end



end

app/views/layouts/_flashnotice.html.erb
<div class="container">
  <div class="row">
    <%if flash[:notice] %>
      <div class="alert alert-success"><%=flash[:notice] %></div>
    <%end %>

    <%if flash[:alert] %>
      <div class="alert alert-danger"><%=flash[:alert] %></div>
    <%end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="row d-flex">

    <div class="col-12 col-md d-flex justify-content-center justify-content-md-start ">
      <a href="<%=root_path %>" class="logo text-decoration-none align-self-center">Events Hub</a>
    </div>

    <div class="col d-flex my-3 justify-content-center justify-content-md-end ">
      <div class="nav-buttons d-flex">
        <%= link_to "Browse Events", events_path, class:"p-2 text-decoration-none" %>
        <%if current_user_admin? %>
          <%= link_to "Create Event", new_event_path, class:"p-2 text-decoration-none" %>
          <%= link_to "All Users", users_path, class:"p-2 text-decoration-none" %>
        <%end %>


        <%if current_user %>
          <%= link_to "My Profile", current_user, class:"p-2 text-decoration-none" %>
          <%= link_to "Sign Out", session_path, method: :delete, class:"p-2 text-decoration-none" %>
        <%else %>
          <%= link_to "Sign Up", signup_path, class:"p-2 text-decoration-none" %>
          <%= link_to "Sign In", new_session_path, class:"p-2 text-decoration-none" %>
        <%end %>
      </div>
    </div>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events25</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Google Material Icons Imported As Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashnotice' %>
    <%= render 'layouts/footer' %>

    <%= yield %>
  </body>
</html>